Rov 32
rovisor/rovisor-ui pull request #10
Opened 2023-10-29 16:21 UTC by Varuno8

2023-10-29 16:32 UTC, rachittyagi requested changes

2023-10-29 16:32 UTC, rachittyagi commented on signup.html
> +      body {
move all the style to css/style.css

2023-10-29 16:32 UTC, rachittyagi commented on signup.html
> +            style="border: none; background: transparent; cursor: pointer"
remove the inline style and add a class for it

2023-10-29 16:32 UTC, rachittyagi commented on signup.html
> +              src="pngwing.com (1) copy.png"
move all the images to assets/img folder and add reference from there

2023-10-29 16:32 UTC, rachittyagi commented on signup.html
> +          >&gt
remove &gt

2023-10-29 16:32 UTC, rachittyagi commented on signup.html
> +          style="
remove inline style and add class for it

2023-10-29 16:32 UTC, rachittyagi commented on signup.html
> +      <img src="photo_2023-10-21 21.01.13.jpeg" alt="Logo" class="logo" />
move the image to assets/img folder and add reference form there

2023-10-29 16:33 UTC, rachittyagi commented on signup.html
> +      body {
And change the title to Sign Up

2023-10-30 11:35 UTC, closed without merging

2023-10-30 11:36 UTC, yaneshtyagi commented
Branch is not ready for merging. Closing this PR as this story should go back to backlog.