Rov 72 generate an angular component named registration 2
rovisor/rovisor-ui pull request #17
Opened 2023-11-22 19:47 UTC by Vedant-Tyagi

Made the angular  component .

2023-11-23 16:24 UTC, yaneshtyagi requested changes

2023-11-23 16:24 UTC, yaneshtyagi commented on src/app/application/registration 2/registration 2.component.ts
> +export class registration {
1. Never ever have space in source code file names or folders. Rename it to `registration` or `registration-v2` if you must have version numbers.
2. Registration must go inside the `signup` module.

2023-11-23 16:52 UTC, rachittyagi commented on src/app/application/registration 2/registration 2.component.ts
> +export class registration {
@yaneshtyagi signup module is different, this registration-v2 is for learning purpose. We will leavrage this later user profile component.

2023-11-24 07:35 UTC, yaneshtyagi commented on src/app/application/registration 2/registration 2.component.ts
> +export class registration {
OK.

2023-11-29 16:43 UTC, rachittyagi approved these changes

2023-11-29 16:45 UTC, Vedant-Tyagi commented on src/app/application/registration 2/registration 2.component.ts
> +export class registration {
Changed the name of the component

2023-11-29 16:46 UTC, rachittyagi approved these changes

2023-11-29 18:42 UTC, merged