Rov 87 add other properties of the user in the reactive form and UI
rovisor/rovisor-ui pull request #21
Opened 2023-12-10 16:22 UTC by Vedant-Tyagi

Add the email, phone number, calendar, password, and country dropdown enum

2023-12-10 16:33 UTC, rachittyagi requested changes

2023-12-10 16:33 UTC, rachittyagi commented on src/app/application/registration-v2/registration-v2.component.html
> +      <input type="date" class="form-control" id="date" >
this should be calendar control

2023-12-10 16:33 UTC, rachittyagi commented on src/app/application/registration-v2/registration-v2.component.html
> +            <input type="text" class="form-control" id="phone" placeholder="Phone Number/Mobile ">
add the formControlName to all the input controls

2023-12-10 16:33 UTC, rachittyagi commented on src/app/application/registration-v2/registration-v2.component.html
> +          <select type="dropdown" class="form-control" id="dropdown">
this should be ng-select component

2023-12-10 16:33 UTC, rachittyagi commented on src/app/application/registration-v2/registration-v2.component.ts
> +    dropdown: new FormControl('',[Validators.required,]),
dropdown is not proper name for the form element, change it to proper name.

2023-12-19 20:49 UTC, Vedant-Tyagi commented on src/app/application/registration-v2/registration-v2.component.html
> +          <select type="dropdown" class="form-control" id="dropdown">
used the ng-select component

2023-12-19 20:49 UTC, Vedant-Tyagi commented on src/app/application/registration-v2/registration-v2.component.html
> +      <input type="date" class="form-control" id="date" >
used the ngbDatepicker

2023-12-20 17:14 UTC, rachittyagi requested changes

2023-12-20 17:20 UTC, Vedant-Tyagi commented on src/app/application/application.module.ts
> +  bootstrap: [
Because to use the bootstrap in the file

2023-12-20 17:51 UTC, Vedant-Tyagi commented on src/app/application/registration-v2/enum.ts
> +  export const ARRAY = Object.values(Countries);
this line export the enum

2023-12-20 18:05 UTC, Vedant-Tyagi commented on src/app/application/registration-v2/registration-v2.component.ts
> +  countries= ARRAY;
selectedCountry: any; This line declares a variable named selectedCountry and assigns the type any to it.

countries: ARRAY; This line declares a variable named countries and assigns the type ARRAY

2023-12-20 18:05 UTC, Vedant-Tyagi commented on src/app/application/registration-v2/registration-v2.component.ts
>    this.registrationForm = new FormGroup({
Added

2023-12-20 18:05 UTC, Vedant-Tyagi commented on src/app/application/registration-v2/registration-v2.component.ts
> +onDateSelect($event: NgbDate) {
done

2023-12-20 18:06 UTC, Vedant-Tyagi commented on package.json
> +    "ng-multiselect-dropdown": "^1.0.0",
done

2024-01-01 02:57 UTC, rachittyagi commented on src/app/application/registration-v2/registration-v2.component.ts
> +minDate = "2022-12-15";
these dates should not be hard coded.

2024-03-22 19:38 UTC, closed without merging