Rov 78 add other properties of the user in the reactive form and UI
rovisor/rovisor-ui pull request #23
Opened 2023-12-13 22:53 UTC by Varuno8

2023-12-14 05:07 UTC, rachittyagi requested changes

2023-12-14 05:07 UTC, rachittyagi commented on src/app/application/registration-1/registration-1.component.html
> +          class="form-control"
instead of html control, use the ngb-datepicker

2023-12-14 05:07 UTC, rachittyagi commented on src/app/application/registration-1/registration-1.component.html
> +          bindLabel="name"
Enum does not have the name and id property, which may cause error in bindLabel and bindValue. And this one is simple binding from list so ng-template also not required.

2023-12-14 05:07 UTC, rachittyagi commented on src/app/application/registration-1/registration-1.component.ts
> +  countriesInfo: CountryInfo[] = [
you need to use the enum here instead of creating new list

2023-12-18 16:51 UTC, Varuno8 commented on src/app/application/registration-1/registration-1.component.html
> +          class="form-control"
corrected the mistake

2023-12-18 16:53 UTC, Varuno8 commented on src/app/application/registration-1/registration-1.component.html
> +          bindLabel="name"
not able to make the style of options and country same

2023-12-20 16:17 UTC, rachittyagi requested changes

2023-12-20 16:17 UTC, rachittyagi commented on src/app/application/registration-1/countries-list.ts
> +export const ARRAY = Object.values(Countries);
can you please explain me this line

2023-12-20 16:17 UTC, rachittyagi commented on src/app/application/registration-1/registration-1.component.ts
> +  countries = ARRAY;
what value you are assigning here

2023-12-20 17:21 UTC, Varuno8 commented on src/app/application/registration-1/countries-list.ts
> +export const ARRAY = Object.values(Countries);
we are exporting the array which contains country enum

2023-12-20 17:28 UTC, Varuno8 commented on src/app/application/registration-1/registration-1.component.ts
> +  countries = ARRAY;
selectedCountry is not assigning any value,i just took this from the ng-select documentation

2023-12-28 17:01 UTC, rachittyagi requested changes

2023-12-28 17:01 UTC, rachittyagi commented on src/app/application/registration-1/registration-1.component.html
> +          [(ngModel)]="selectedCountry"
ngModel is not needed with formControlName

2023-12-28 17:26 UTC, rachittyagi approved these changes

2023-12-28 17:27 UTC, merged

2023-12-28 17:27 UTC, Varuno8 commented on src/app/application/registration-1/registration-1.component.html
> +          [(ngModel)]="selectedCountry"
removed the ngModel