created a button click function and assigned the values of form field…
rovisor/rovisor-ui pull request #25
Opened 2023-12-19 17:41 UTC by Varuno8

… to variable .

2023-12-20 16:09 UTC, rachittyagi requested changes

2023-12-20 16:09 UTC, rachittyagi commented on src/app/application/registration-1/registration-1.component.ts
> +    if (this.userForm.valid) {
store these values in one single object

2023-12-20 16:45 UTC, Varuno8 commented on src/app/application/registration-1/registration-1.component.ts
> +    if (this.userForm.valid) {
corrected the mistake

2023-12-26 17:16 UTC, rachittyagi submitted a review, later dismissed

2023-12-28 17:37 UTC, rachittyagi approved these changes

2023-12-28 17:38 UTC, merged