Rov 76 validate the fields using typescript
rovisor/rovisor-ui pull request #26
Opened 2023-12-21 23:19 UTC by Varuno8

2023-12-26 17:15 UTC, rachittyagi requested changes

2023-12-26 17:15 UTC, rachittyagi commented on src/app/application/registration-1/registration-1.component.html
> +          <div *ngIf="userForm.get('birthdate').hasError('lessthen87')">
max date error message is missing

2023-12-26 17:15 UTC, rachittyagi commented on src/app/application/registration-1/registration-1.component.html
> +        <input
error message is missing for email validation

2023-12-26 17:15 UTC, rachittyagi commented on src/app/application/registration-1/registration-1.component.html
> +        <input
validation error message for this field is also missing

2023-12-26 17:15 UTC, rachittyagi commented on src/app/application/registration-1/registration-1.component.html
> +        <input
validation error message for this field is also missing

2023-12-26 17:15 UTC, rachittyagi commented on src/app/application/registration-1/registration-1.component.html
> +  <button type="button" class="btn btn-primary" (click)="submitForm()">
disable the button until all fields are validated

2023-12-26 17:33 UTC, Varuno8 commented on src/app/application/registration-1/registration-1.component.html
> +        <input
corrected the mistake

2023-12-26 17:36 UTC, Varuno8 commented on src/app/application/registration-1/registration-1.component.html
> +        <input
corrected the mistake

2023-12-26 17:37 UTC, Varuno8 commented on src/app/application/registration-1/registration-1.component.html
> +          <div *ngIf="userForm.get('birthdate').hasError('lessthen87')">
corrected the mistake

2023-12-26 17:41 UTC, Varuno8 commented on src/app/application/registration-1/registration-1.component.html
> +  <button type="button" class="btn btn-primary" (click)="submitForm()">
corrected the mistake

2023-12-27 16:34 UTC, rachittyagi requested changes

2023-12-27 16:34 UTC, rachittyagi commented on src/app/application/registration-1/registration-1.component.html
> +          <div *ngIf="userForm.get('birthDate').hasError('required')">
formControlName should be exact same as in reactive form declaration.

2023-12-27 16:34 UTC, rachittyagi commented on src/app/application/registration-1/registration-1.component.html
> +          <div *ngIf="userForm.get('birthdate').hasError('lessthen87')">
there should be check for max date as well, future date should not be selectable

2023-12-28 17:46 UTC, rachittyagi approved these changes

2023-12-28 17:46 UTC, merged