add login logo
rovisor/rovisor-ui pull request #3
Opened 2023-09-19 16:05 UTC by Vedant-Tyagi

2023-09-20 14:40 UTC, rachittyagi commented
do not push settings.json, always make sure to commit the files which are related to the particular card or work

2023-09-24 16:23 UTC, rachittyagi requested changes

2023-09-24 17:24 UTC, Vedant-Tyagi commented on index.html
> +                                href="#about">Login</a></li>
I had made the changes that you said me to do

2023-10-02 19:24 UTC, Vedant-Tyagi commented on index.html
> +                                href="#about">Login</a></li>
removed the live server

2023-10-04 05:37 UTC, yaneshtyagi commented on index.html
> +                            <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded"
@Vedant-Tyagi What is the breakpoint for lg-* class?

2023-10-05 18:12 UTC, yaneshtyagi submitted a review, later dismissed

2023-10-26 03:21 UTC, yaneshtyagi approved these changes

2023-10-26 03:22 UTC, yaneshtyagi submitted a review, later dismissed

2023-10-26 03:23 UTC, yaneshtyagi approved these changes

2023-10-26 03:26 UTC, yaneshtyagi approved these changes

2023-10-26 03:28 UTC, merged