Rov 101 user dashboard navigation and file upload
rovisor/rovisor-ui pull request #38
Opened 2024-01-04 12:41 UTC by Varuno8

2024-01-04 16:07 UTC, rachittyagi requested changes

2024-01-04 16:07 UTC, rachittyagi commented on src/app/application/upload-statement/upload-statement.component.html
> +  function validateForm() {
javascript functions not recommended in between of angular code.

2024-01-04 16:07 UTC, rachittyagi commented on src/app/application/upload-statement/upload-statement.component.html
> +    <svg
use the bi icons instead of svg

2024-01-04 16:07 UTC, rachittyagi commented on src/app/application/upload-statement/upload-statement.component.html
> +<style>
no style tag,  there is separate file for adding the style

2024-01-04 16:07 UTC, rachittyagi commented on src/app/application/upload-statement/upload-statement.component.html
> +  <div class="modal-header" style="background-color: #d9d9d9; height: 30px">
instead of inline styles add the class and put the style into the component css file

2024-01-05 16:24 UTC, rachittyagi requested changes

2024-01-05 16:24 UTC, rachittyagi commented on package.json
> +    "@angular/material": "^13.0.0",
we are not using material so @angular/material is not required, please uninstall this package.

2024-01-05 16:24 UTC, rachittyagi commented on src/app/application/application-routing.module.ts
> +      {
upload-statement is modal, so no route is needed. Please remove this.

2024-01-05 16:39 UTC, Varuno8 commented on src/app/application/upload-statement/upload-statement.component.html
> +  <div class="modal-header" style="background-color: #d9d9d9; height: 30px">
added classes

2024-01-07 17:59 UTC, rachittyagi approved these changes

2024-01-07 17:59 UTC, merged