Varun/rov 12
rovisor/rovisor-ui pull request #4
Opened 2023-09-19 17:17 UTC by Varuno8

please review my code

2023-09-24 16:22 UTC, rachittyagi requested changes

2023-10-01 13:51 UTC, Varuno8 commented on contact.html
> +            <form>
updated the code

2023-10-01 20:33 UTC, yaneshtyagi requested changes

2023-10-01 20:33 UTC, yaneshtyagi commented on contact.html
> +            src="/Users/varuntyagi/Downloads/WhatsApp Image 2023-09-17 at 20.20.54.jpeg"
Do not use absolute path for the assets (like images). Instead use relative path.

2023-10-01 20:33 UTC, yaneshtyagi commented on contact.html
> +              placeholder="Phone Number"
Inconsistent grammar. Use sentence case like other fields for placeholder text.

2023-10-01 20:33 UTC, yaneshtyagi commented on contact.html
> +        if (fullName && email && phone && message) {
If a user enters a bunch of spaces (e.g. "      ") in full name or message, this validation will fail. Trim these fields to remove leading and trailing spaces before checking if these have any value.

2023-10-02 22:31 UTC, Varuno8 commented on contact.html
> +            src="/Users/varuntyagi/Downloads/WhatsApp Image 2023-09-17 at 20.20.54.jpeg"
I will update the code ASAP

2023-10-02 23:55 UTC, Varuno8 commented on contact.html
> +            src="/Users/varuntyagi/Downloads/WhatsApp Image 2023-09-17 at 20.20.54.jpeg"
I understand, and I will correct this mistake.

2023-10-05 18:09 UTC, yaneshtyagi requested changes

2023-10-05 18:09 UTC, yaneshtyagi commented on contact.html
> +              placeholder="Phone Number"
"Phone Number" change is not resolved.

2023-10-05 18:09 UTC, yaneshtyagi commented on contact.html
> +        if (fullName && email && phone && message) {
The condition is not updated.

2023-10-08 00:04 UTC, closed without merging