Rov 114 show server success and error message on file upload
rovisor/rovisor-ui pull request #50
Opened 2024-02-21 21:06 UTC by Varuno8

2024-02-22 14:44 UTC, rachittyagi requested changes

2024-02-22 14:44 UTC, rachittyagi commented on src/app/application/upload-statement/state/upload-statement.service.ts
> +        return this.httpClient.post('apiUrl', formData)
the 'apiUrl'  should be without quotes

2024-02-22 14:44 UTC, rachittyagi commented on src/app/application/upload-statement/state/upload-statement.service.ts
> +                    this.toastr.success('File uploaded successfully', 'Success');
the toastr should be at component level instead of service

2024-02-22 21:32 UTC, Varuno8 commented on src/app/application/upload-statement/state/upload-statement.service.ts
> +        return this.httpClient.post('apiUrl', formData)
removed the quotes

2024-02-22 21:34 UTC, Varuno8 commented on src/app/application/upload-statement/state/upload-statement.service.ts
> +        return this.httpClient.post('apiUrl', formData)
resolved the error

2024-02-22 21:34 UTC, Varuno8 commented on src/app/application/upload-statement/state/upload-statement.service.ts
> +        return this.httpClient.post('apiUrl', formData)
removed the quotes

2024-02-25 14:56 UTC, rachittyagi approved these changes

2024-02-25 14:56 UTC, merged