Rov 125 account onboard develop the UI for adding a new account
rovisor/rovisor-ui pull request #55
Opened 2024-03-04 10:03 UTC by Varuno8

2024-03-06 18:20 UTC, rachittyagi requested changes

2024-03-06 18:20 UTC, rachittyagi commented on src/app/application/add-account/add-account.component.css
> +input, select {
use the bootstrap form classes instead of writing own css

2024-03-06 18:20 UTC, rachittyagi commented on src/app/application/add-account/add-account.component.css
> +button {
use the bootstrap button classes instead of writing own css

2024-03-06 18:20 UTC, rachittyagi commented on src/app/application/add-account/add-account.component.html
> +      <select class="form-select" id="accountSelect" formControlName="selectedAccount">
make it a list array and use ng-select

2024-03-06 18:20 UTC, rachittyagi commented on src/app/application/add-account/add-account.component.html
> +      <input type="typeofaccount" id="accountNumber" formControlName="accountNumber" />
typeofaccount is not a valid type for input, this should accept alphanumeric.

2024-03-06 18:20 UTC, rachittyagi commented on src/app/application/add-account/add-account.component.html
> +      <input type="text" id="accountName" formControlName="accountName" />
invalid message is missing on all the fields.

2024-03-08 23:32 UTC, Varuno8 commented on src/app/application/add-account/add-account.component.html
> +      <input type="text" id="accountName" formControlName="accountName" />
> invalid message is missing on all the fields.

but there is already button disabled, so how do we show the invalid message if the button will not come until the validations are fulfilled?

2024-03-11 21:11 UTC, Varuno8 commented on src/app/application/add-account/add-account.component.css
> +button {
resolved

2024-03-12 11:25 UTC, rachittyagi requested changes

2024-03-12 11:25 UTC, rachittyagi commented on src/app/application/add-account/add-account.component.ts
> +    this.accountForm.patchValue({
why we are setting this value?

2024-03-12 11:25 UTC, rachittyagi commented on src/app/application/add-account/add-account.component.ts
> +    this.accountForm.valueChanges.subscribe(() => { // This line sets up a subscription to the valueChanges observable of the accountForm
this subscribe is not required, why we making all the fields touched?

2024-03-12 11:25 UTC, rachittyagi commented on src/app/application/add-account/add-account.component.ts
> +    else {
this condition will never be true, as we are already checking form valid on html

2024-03-13 15:32 UTC, rachittyagi approved these changes

2024-03-13 15:34 UTC, merged