Rov 162 account s home screen UI
rovisor/rovisor-ui pull request #71
Opened 2024-04-14 23:26 UTC by Varuno8

2024-04-15 19:06 UTC, rachittyagi requested changes

2024-04-15 19:06 UTC, rachittyagi commented on src/app/application/account-details/account-details.component.css
> +.account-name {
use the standard css from the style.css

2024-04-15 19:06 UTC, rachittyagi commented on src/app/application/account-details/account-details.component.css
> +.secondary-text {
use `.text-secondary` class for this

2024-04-15 19:06 UTC, rachittyagi commented on src/app/application/account-details/account-details.component.css
> +  color: #6c757d;
use the existing css class for this

2024-04-15 19:06 UTC, rachittyagi commented on src/app/application/account-details/account-details.component.html
> +      <h1 class="account-name">{{ accountName }}</h1>
this text should be in-line with the upload button

2024-04-15 19:06 UTC, rachittyagi commented on src/app/application/account-details/account-details.component.css
> +.box-title {
use the css class from the existing bootstrap one's or style.css

2024-04-15 19:06 UTC, rachittyagi commented on src/app/application/account-details/account-details.component.html
> +        <h5 class="box-title">Opening Balance</h5>
this text should be center aligned

2024-04-15 19:06 UTC, rachittyagi commented on src/app/application/account-details/account-details.component.html
> +        <h5 class="box-title">Credit Amount</h5>
this should be center-aligned

2024-04-15 19:06 UTC, rachittyagi commented on src/app/application/account-details/account-details.component.html
> +        <h5 class="box-title debit-text">Debit Amount</h5>
this should be center-aligned

2024-04-15 19:06 UTC, rachittyagi commented on src/app/application/account-details/account-details.component.html
> +        <h5 class="box-title">Closing Balance</h5>
this should be center-aligned

2024-04-15 19:06 UTC, rachittyagi commented on src/app/application/account-details/account-details.component.ts
> +        this.accountName = result.AccountName; // Update accountName with the retrieved account name
why we are holding this in a separate variable?

2024-04-16 14:05 UTC, Varuno8 commented on src/app/application/account-details/account-details.component.html
> +        <h5 class="box-title">Closing Balance</h5>
resolved

2024-04-16 17:28 UTC, Varuno8 commented on src/app/application/account-details/account-details.component.css
> +.account-name {
what is the style.css meaning?

2024-04-20 23:54 UTC, Varuno8 commented on src/app/application/account-details/account-details.component.css
> +  color: #6c757d;
used the style.css for colour or font size but for customised margin I have to make these classes in acc-detail.comp.css file

2024-04-22 15:45 UTC, rachittyagi approved these changes

2024-04-22 15:46 UTC, merged