ROV-161-Home-dashboard-UI
rovisor/rovisor-ui pull request #72
Opened 2024-04-15 14:51 UTC by Vedant-Tyagi

2024-04-15 19:12 UTC, rachittyagi requested changes

2024-04-15 19:12 UTC, rachittyagi commented on src/app/application/dashboard/dashboard.component.css
> +.font{
don't declare font size here and there, use the existing font-size class from style.css

2024-04-15 19:12 UTC, rachittyagi commented on src/app/application/dashboard/dashboard.component.css
> +.no-underline{
use the existing `.text-decoration-none` class for this

2024-04-15 19:12 UTC, rachittyagi commented on src/app/application/dashboard/dashboard.component.html
> +                        style="background-color:#DBDEE7;">
don't use inline styles

2024-04-15 19:12 UTC, rachittyagi commented on src/app/application/dashboard/dashboard.component.html
> +                    <input class="form-control " style="background-color:#DBDEE7" type="search" aria-label="Search">
don't use inline styles

2024-04-15 19:12 UTC, rachittyagi commented on src/app/application/dashboard/dashboard.component.html
> +                    <input class="form-control " style="background-color:#DBDEE7" type="search" aria-label="Search">
what does `aria-label` mean

2024-04-15 19:12 UTC, rachittyagi commented on src/app/application/dashboard/dashboard.component.html
> +    <div class="row card m-4" style=" background-color:#FEF7E5;">
no inline-style please

2024-04-15 19:12 UTC, rachittyagi commented on src/app/application/dashboard/dashboard.component.html
> +                [items]="items2"
give proper variable name

2024-04-15 19:12 UTC, rachittyagi commented on src/app/application/dashboard/dashboard.component.html
> +                [items]="items"
give proper variable name

2024-04-15 19:12 UTC, rachittyagi commented on src/app/application/dashboard/dashboard.component.html
> +            <a href="app/consolidate-statement"
this should be button with click event

2024-04-15 19:12 UTC, rachittyagi commented on src/app/application/dashboard/dashboard.component.ts
> +    { id: 4, name:'Tranfer'},
spelling mistake

2024-04-15 19:12 UTC, rachittyagi commented on src/app/application/dashboard/dashboard.component.ts
> +    this.model = { year: 2024, month: 4, day: 12 }
why hard coded date?

2024-04-20 19:47 UTC, Vedant-Tyagi commented on src/app/application/dashboard/dashboard.component.ts
> +    { id: 4, name:'Tranfer'},
changed

2024-04-20 19:47 UTC, Vedant-Tyagi commented on src/app/application/dashboard/dashboard.component.html
> +                [items]="items2"
changed

2024-04-20 19:48 UTC, Vedant-Tyagi commented on src/app/application/dashboard/dashboard.component.html
> +                    <input class="form-control " style="background-color:#DBDEE7" type="search" aria-label="Search">
done

2024-04-20 19:48 UTC, Vedant-Tyagi commented on src/app/application/dashboard/dashboard.component.html
> +                        style="background-color:#DBDEE7;">
done

2024-04-20 19:48 UTC, Vedant-Tyagi commented on src/app/application/dashboard/dashboard.component.css
> +.no-underline{
done

2024-04-20 19:49 UTC, Vedant-Tyagi commented on src/app/application/dashboard/dashboard.component.css
> +.font{
done

2024-04-20 19:49 UTC, Vedant-Tyagi commented on src/app/application/dashboard/dashboard.component.html
> +                [items]="items"
done

2024-04-21 16:16 UTC, Vedant-Tyagi commented on src/app/application/dashboard/dashboard.component.html
> +                    <input class="form-control " style="background-color:#DBDEE7" type="search" aria-label="Search">
attribute provides a label for the search input field, making it more accessible to users who rely on screen readers.

2024-04-21 16:17 UTC, Vedant-Tyagi commented on src/app/application/dashboard/dashboard.component.html
> +    <div class="row card m-4" style=" background-color:#FEF7E5;">
done

2024-04-22 22:12 UTC, rachittyagi approved these changes

2024-04-22 22:12 UTC, merged