ROV-166-Auto-fill-filter-options
rovisor/rovisor-ui pull request #74
Opened 2024-04-24 18:52 UTC by Vedant-Tyagi

2024-04-29 03:39 UTC, yaneshtyagi requested changes
Not working as expected.

2024-05-16 04:47 UTC, yaneshtyagi commented
@ellipsis review this PR.

2024-05-21 13:17 UTC, quy-rov requested changes
Changes Required. Majorly, the category filter on dashboard does not have any mapping on the consolidated statement page.

2024-05-21 13:17 UTC, quy-rov commented on src/app/application/consolidate-statement/consolidate-statement.component.ts
> +      this.fetchStatements();
this is duplicate call to the same function, please avoid.

2024-05-21 13:17 UTC, quy-rov commented on src/app/application/consolidate-statement/consolidate-statement.component.ts
> +        transactionType: params['transactionType']? JSON.parse(params['toDate']) : null,
Why you are mapping `transactionType` to `toDate`?

2024-05-21 13:17 UTC, quy-rov commented on src/app/application/dashboard/dashboard.component.html
> +        <div class="form-group">
This category filter is not there on Consolidate statement page, how can I map its value?

2024-05-21 15:57 UTC, yanshityagi commented on src/app/application/dashboard/dashboard.component.html
> +        <div class="form-group">
@quy-rov Currently we are not mapping the value of the category filter.

2024-05-21 16:53 UTC, Vedant-Tyagi commented on src/app/application/consolidate-statement/consolidate-statement.component.ts
> +      this.fetchStatements();
okay

2024-05-21 16:54 UTC, Vedant-Tyagi commented on src/app/application/consolidate-statement/consolidate-statement.component.ts
> +        transactionType: params['transactionType']? JSON.parse(params['toDate']) : null,
I have changed the mapping

2024-05-21 17:12 UTC, Vedant-Tyagi commented on src/app/application/dashboard/dashboard.component.html
> +        <div class="form-group">
using query params  and redirecting the page using that

2024-05-29 11:05 UTC, Vedant-Tyagi commented on src/app/application/dashboard/dashboard.component.ts
>        category: this.statementFiltersForm.value?.category
It appears that there is no option available on the consolidated statement page. Additionally, I have been instructed not to apply filters if the option is absent.

2024-05-30 17:09 UTC, yanshityagi commented on src/app/application/dashboard/dashboard.component.ts
>      const selectedFilters = {
@Varuno8 @Vedant-Tyagi If the user does not select any option for Transaction Type on the home screen then the default option will be 'All'. 
So, in this case, if nothing is selected then on the consolidated statement screen the option 'All' should be selected in Transaction Type.

@Vedant-Tyagi Please show "All" as default selected option.

2024-07-17 18:47 UTC, closed without merging