Rov 12
rovisor/rovisor-ui pull request #8
Opened 2023-10-16 17:15 UTC by Varuno8

please review my code

2023-10-16 17:56 UTC, rachittyagi requested changes

2023-10-16 17:56 UTC, rachittyagi commented on contact.html
> +        var email = document.getElementById("email").value;
add trim for email & phone number. 
validate if phone number is numeric and its length is 10. 
check if email is in correct format.

2023-10-21 17:12 UTC, Varuno8 commented on contact.html
> +        var email = document.getElementById("email").value;
code updated

2023-10-26 04:01 UTC, yaneshtyagi approved these changes

2023-10-26 14:47 UTC, merged