Rov 191 create a calculator to calculate monthly emi
rovisor/rovisor-ui pull request #80
Opened 2024-06-12 00:10 UTC by Varuno8

2024-06-16 16:08 UTC, Vedant-Tyagi commented on src/app/application/emi-calculator/emi-calculator.component.html
> +<p class="page_subtitle  text-subtitle">Calculate monthly EMI</p>
change the font weight it should be more bold

2024-06-16 16:08 UTC, Vedant-Tyagi commented on src/app/application/emi-calculator/emi-calculator.component.html
> +<h1 class="emi text-bold">EMI Calculator</h1>
page should be responsive

2024-06-28 05:57 UTC, yaneshtyagi commented
@Vedant-Tyagi please review this PR.

2024-06-28 07:47 UTC, Vedant-Tyagi commented
@yaneshtyagi  this card is still in process may be varun is  working on this card once he completes his work and pushed it into review then I will be reviewing this

2024-06-30 17:31 UTC, Vedant-Tyagi submitted a review, later dismissed
It seems to be working fine and I found no error

2024-06-30 17:41 UTC, yaneshtyagi commented
@Vedant-Tyagi What is the responsibility of `CalculatorComponent` class? Is the name of the class appropriate?

2024-07-14 10:06 UTC, yaneshtyagi commented
> @Vedant-Tyagi What is the responsibility of `CalculatorComponent` class? Is the name of the class appropriate?

@Vedant-Tyagi Please respond to this comment.

2024-07-14 10:11 UTC, yaneshtyagi requested changes
Please resolve the conflicts.

2024-07-14 16:17 UTC, Vedant-Tyagi commented
> > @Vedant-Tyagi What is the responsibility of `CalculatorComponent` class? Is the name of the class appropriate?
> 
> @Vedant-Tyagi Please respond to this comment.
> @yaneshtyagi  This calculator is used to determine the Monthly EMI, the Total Interest Paid, and the Total Amount, which is the product of the principal amount and the total time period.

2024-07-14 17:40 UTC, yaneshtyagi commented
When you are resolving the merge conflicts, you should have understood that naming a class appropriately is important. Generic names like `CalculatorComponent` cause the problems since we have many calculators. I expect such issues to be pointed out during code review.

2024-07-14 18:18 UTC, Varuno8 commented
> When you are resolving the merge conflicts, you should have understood that naming a class appropriately is important. Generic names like `CalculatorComponent` cause the problems since we have many calculators. I expect such issues to be pointed out during code review.

it was my first card, apologies for that mistake, I pointed the same mistake on the next card

2024-07-14 19:04 UTC, yaneshtyagi commented
No need for apologies. It's all part of learning.

2024-07-16 17:09 UTC, Vedant-Tyagi commented
@yaneshtyagi  I have reviewed and the conflict has been resolved and functionality is also working fine

2024-07-16 17:17 UTC, Vedant-Tyagi approved these changes

2024-07-16 17:18 UTC, Vedant-Tyagi approved these changes

2024-07-16 17:40 UTC, yaneshtyagi approved these changes

2024-07-16 17:40 UTC, merged