Added Simple Interest Calculator component and route to application m…
rovisor/rovisor-ui pull request #89
Opened 2024-07-07 13:54 UTC by Varuno8

…odule and routing module, and updated sidebar.json with new menu item

2024-07-07 15:37 UTC, Vedant-Tyagi submitted a review, later dismissed
Reviewed the card, and I found it to be working fine

2024-07-14 10:09 UTC, yaneshtyagi requested changes
Please resolve the conflicts.

2024-07-18 16:50 UTC, Vedant-Tyagi approved these changes
The card functionality is working fine and all the conflict has resolved

2024-07-18 16:56 UTC, yaneshtyagi approved these changes

2024-07-18 16:56 UTC, merged