ROV-202-Develop-Emergency-Fund-Calculator
rovisor/rovisor-ui pull request #90
Opened 2024-07-08 15:31 UTC by Vedant-Tyagi

2024-07-11 14:22 UTC, Varuno8 submitted a review, later dismissed

2024-07-14 10:10 UTC, yaneshtyagi requested changes
Please resolve the conflicts.

2024-07-14 17:15 UTC, Vedant-Tyagi commented
@yaneshtyagi  The conflict has been resolved.

2024-07-14 17:33 UTC, yaneshtyagi commented
@Varuno8 @Vedant-Tyagi After conflict resolution, PR needs to be approved again.

2024-07-16 14:46 UTC, Varuno8 approved these changes

2024-07-17 17:22 UTC, Varuno8 approved these changes

2024-07-17 17:29 UTC, yaneshtyagi approved these changes

2024-07-17 17:30 UTC, merged